import { AuthProvider } from "@/components/AuthProvider";
import LoginPanel from "@/components/LoginPanel";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-ignore: CSS module type declarations are not present in this project
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <AuthProvider>
          {/* Top bar */}
          <header className="flex justify-end px-6 py-3 border-b border-zinc-800">
            <LoginPanel />
          </header>

          {children}
        </AuthProvider>
      </body>
    </html>
  );
}